### ISSUE TITLE
Confused about Mac download file

### ISSUE THREAD

**Issue by irish-moss** [JoshuaPostel/DeepGliss#17] opened 2022-07-14 15:27 UTC
Is this file supposed to be DeepGliss.dylib ? 

Ableton doesn't recognize it in VST folder. I've never seen this file suffix before. Mac says it's a linux file.

**Comment by JoshuaPostel** [comment] 2022-07-20 12:52
Thank you very much for reporting this.  [Looks like](https://helpcenter.steinberg.de/hc/en-us/articles/115000171310-VST-plug-in-locations-on-Mac-OS-X-and-macOS) I should have named the file `DeepGliss.vst` for the Mac release.  I will fix the release page, but in the mean time you could rename the file extension.

Please be aware that currently the plugin does not work on apple silicon (e.g. M1 chips), see #18 for details.

**Comment by irish-moss** [comment] 2022-07-20 13:34
I tried renaming the file. Ableton doesn't see it unfortunately. Intel mac

**Comment by JoshuaPostel** [comment] 2022-07-21 12:30
Thanks again for the feedback (especially the OS and live version).  I will look into this and remove the mac release until I have verified a working version.

**Comment by nay-seven** [comment] 2022-07-21 21:00
Hello, same here
Daw( last version): Bespoke & Usine Hollyhock
MacOs Mojave

**Comment by nay-seven** [comment] 2022-07-24 20:34
last version 0.1.5 ( vst) visible now in Bespoke, need to study more with Aalto ( MPE mode and pitchbend setted) to make sure it works as intended.
also visible in Usine, but Gui issue ( lines visible but no menu)
MacOs Mojave

**Comment by nay-seven** [comment] 2022-07-24 20:47
so i confirm it work here, tested in live ableton 11 lite with Aalto and Vital
at first same issue than Usine about gui, but if i move the interface to my second screen, it's ok, so looks retina is not supported for these 2 daws (?) ( ok in Bespoke)
mojave macbook pro 2015

**Comment by irish-moss** [comment] 2022-07-24 21:42
Please hit me a download link when I can test on Live 10
Thanks
Rob

**Comment by nay-seven** [comment] 2022-07-24 21:53
@irish-moss check last release ?

**Comment by JoshuaPostel** [comment] 2022-07-25 16:37
@nay-seven thank you very much for testing the `0.1.5` release and reporting the results. I am happy to hear that DeepGliss is finally running on MacOS.

For now I am going to focus on the most mainstream DAWs (Ableton, FL Studio, etc), hopefully sorting out issues there will also resolve issues in Bespoke and Usine.

I created issue #22 to track retina display issues.

**Comment by JoshuaPostel** [comment] 2022-07-25 16:38
@irish-moss yes, I have updated the MacOS release file if you would like to test it out: [download link](https://github.com/JoshuaPostel/DeepGliss/releases/download/0.1.5/DeepGliss.vst.zip)

**Comment by irish-moss** [comment] 2022-07-25 16:45
Thanks man!

**Comment by nay-seven** [comment] 2022-07-25 16:45
@JoshuaPostel  always glad to help cool projects ;-)
Btw, don't know if you use Facebook, but i have share DeepGliss [on my group](https://www.facebook.com/groups/2147926972195324) , looks people are interested ;-)

**Comment by irish-moss** [comment] 2022-07-25 16:48
cool

**Comment by irish-moss** [comment] 2022-07-25 17:38
I can select from the top menu but I cannot draw or connect anything for
some reason in the body of the plug in. I'm confused.
R

**Comment by nay-seven** [comment] 2022-07-25 19:20
Joshua will complete, but as far i understand, nothing to draw or to connect...
Connect your midi keyboard /to deepgliss /deepgliss to a plugin 
set the same pitchbend range in deepgliss setting than your plugin
activate MPE in your plugin
play a low chord, then a higher chord, you'll see the lines..( more a monitor than a patch editor)

**Comment by irish-moss** [comment] 2022-07-25 20:21
Where on say Vital is MPE activated? I have glide and legato on

**Comment by irish-moss** [comment] 2022-07-25 20:25
i found it

**Comment by irish-moss** [comment] 2022-07-25 20:30
Got it. I had to remove the fx chain before Deep Gliss and put Vital on a
separate track. Now I'm seeing and hearing it. Thanks for your time Joshua
Rob

**Comment by irish-moss** [comment] 2022-07-25 20:34
Ok it's working now. Only issue is it pops at the attack of every chord and
my cpu isn't high. Not sure why
Rob

**Comment by JoshuaPostel** [comment] 2022-07-26 03:07
> Only issue is it pops at the attack of every chord and my cpu isn't high. Not sure why

this is an issue with DeepGliss (see #5), likely due to cpu usage.  Hopefully I can make performance improvements in the near future.

**Comment by JoshuaPostel** [comment] 2022-07-26 03:56
Thank you both for reporting and working though the MacOS download file mishap.  I'm closing this issue, but feel free to open others or comment on the ones linked.

**Closed by JoshuaPostel** 2022-07-26 03:56 UTC

**Comment by irish-moss** [comment] 2022-10-11 08:43
It's coming up in Ableton after synth in signal path. Now.....wtf am I
doing is beyond me! LOL
Rob
